"""update database

Revision ID: 63c5b3ca973e
Revises: b1c7b028a312
Create Date: 2020-05-11 20:30:13.681727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63c5b3ca973e'
down_revision = 'b1c7b028a312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('date_posted', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('password_secure', sa.String(length=255), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
    op.drop_column('users', 'password_secure')
    op.drop_column('blogs', 'date_posted')
    # ### end Alembic commands ###
