"""update database

Revision ID: b1c7b028a312
Revises: 44bec3d72fec
Create Date: 2020-05-11 16:59:39.934944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c7b028a312'
down_revision = '44bec3d72fec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('subscribers_blog_id_fkey', 'subscribers', type_='foreignkey')
    op.drop_constraint('subscribers_user_id_fkey', 'subscribers', type_='foreignkey')
    op.drop_column('subscribers', 'user_id')
    op.drop_column('subscribers', 'blog_id')
    op.drop_column('subscribers', 'title')
    op.drop_column('subscribers', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('comment', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('subscribers', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('subscribers', sa.Column('blog_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('subscribers', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('subscribers_user_id_fkey', 'subscribers', 'users', ['user_id'], ['id'])
    op.create_foreign_key('subscribers_blog_id_fkey', 'subscribers', 'blogs', ['blog_id'], ['id'])
    op.drop_table('comments')
    # ### end Alembic commands ###
